
title="Altibase Monitoring Elements"

[[monitor_query]]
series_name ="altibase_basic_info"
tags=[]
fields=["DB_NAME","PRODUCT_VERSION", "STARTUP_PHASE", "NLS_CHARACTERSET", "LOG_MODE", "DB_UP_TIME"]
pivot=false
enable=true
sql="""
select
             d.db_name
            ,v.PRODUCT_VERSION
            ,i.STARTUP_PHASE
            ,n.NLS_CHARACTERSET
            ,decode(a.ARCHIVE_MODE,1,'Archive log', 'No archive log') as LOG_MODE 
            ,decode(i.STARTUP_TIME_SEC, 0, '0', to_char( to_date('1970010109','YYYYMMDDHH') +   i.STARTUP_TIME_SEC/ (60*60*24), 'YYYY/MM/DD HH:MI:SS' ) ) as DB_UP_TIME
from  v$database d
     ,v$version  v
     ,v$instance i
     ,( select NLS_CHARACTERSET
        from  v$nls_parameters
        limit 1
      ) n
     , v$archive a
"""


[[monitor_query]]
series_name ="altibase_mem_stat"
tags=[]
fields=["MEM_MAX_SIZE", "ALLOC_DB_SIZE", "MEM_USED_RATIO", "BUFFER_SIZE"]
pivot=false
enable=true
sql="""
 select
             MEM_MAX_DB_SIZE
           ,(MEM_ALLOC_PAGE_COUNT * 32 * 1024) as  ALLOC_DB_SIZE
           ,((MEM_ALLOC_PAGE_COUNT * 32 * 1024) / MEM_MAX_DB_SIZE )  * 100 AS MEM_USED_RATIO
           ,(SELECT  POOL_SIZE * PAGE_SIZE  FROM V$BUFFPOOL_STAT ) AS BUFFER_SIZE
 from
          v$database
"""

[[monitor_query]]
series_name ="altibase_buffhit_stat"
tags=[]
fields=["HIT_RATIO"]
pivot=false
enable=true
sql="""
  select
          (GET_PAGES + FIX_PAGES - READ_PAGES) / ( GET_PAGES + FIX_PAGES) * 100.00 as HIT_RATIO
  from   V$BUFFPOOL_STAT
 """ 

[[monitor_query]]
series_name ="altibase_session_stat"
tags=[]
fields=["CURRENT_SESSION_CNT", "EXEC_SESSION_CNT", "MAX_CLIENT_CNT"]
pivot=false
enable=true
sql="""
  select
       ( select count(*)  from v$session )                               as CURRENT_SESSION_CNT
      ,( select count(*)  from v$session  where task_state='EXECUTING' ) as EXEC_SESSION_CNT
      ,( select to_number(value1)    from v$property where name = 'MAX_CLIENT'    ) as MAX_CLIENT_CNT
  from dual
"""

[[monitor_query]]
series_name ="altibase_plancache_stat"
tags=[]
fields=["MAX_CACHE_SIZE", "CURRENT_CACHE_SIZE", "CACHE_MISS_COUNT", "CACHE_MISS_RATIO"]
pivot=false
enable=true
sql="""
 select
       MAX_CACHE_SIZE
      ,CURRENT_CACHE_SIZE
      ,CACHE_MISS_COUNT
      ,100.00 -  ( CACHE_MISS_COUNT/(CACHE_HIT_COUNT+CACHE_MISS_COUNT) * 100.00 )  AS CACHE_MISS_RATIO
 from V$SQL_PLAN_CACHE
"""

[[monitor_query]]
series_name ="altibase_servicethread_stat"
tags=[]
fields=["STATE", "CNT"]
pivot_key = "STATE"
pivot=true
enable=true
sql="""
     SELECT 
            STATE
          , COUNT(*) AS CNT
    FROM V$SERVICE_THREAD
    GROUP BY STATE
UNION ALL
      SELECT 
           'TOTAL' AS STATE
           ,COUNT(*)
      FROM V$SERVICE_THREAD        
UNION ALL
      SELECT
           RUN_MODE AS STATE
          ,COUNT(*)
      FROM V$SERVICE_THREAD
      GROUP BY RUN_MODE   
"""
