{
 "title": "AMS  Total dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "시스템 메모리여유율(DB01)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "시스템메모리여유율",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"available_percent\") AS \"Available Percent\" FROM \"mem\" WHERE (\"host\" = 'MyLinuxDB01') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Available Percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" }
     ]
    }
   ]
  },
  { "title": "Panel Title", "type": "vonage-status-panel", "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 } },
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "시스템 CPU IDLE(%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "CPU IDLE" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_idle\") AS \"idle\" FROM \"cpu\" WHERE (\"host\" = 'MyLinuxDB01') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100-mean(\"usage_idle\") AS \"CPU_TOTAL\" FROM \"cpu\" WHERE (\"host\" = 'MyLinuxDB01' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_system\") AS \"CPU_SYSTEM\" FROM \"cpu\" WHERE (\"host\" = 'MyLinuxDB01' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_user\") AS \"CPU_USER\" FROM \"cpu\" WHERE (\"host\" = 'MyLinuxDB01' AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "시스템 디스크사용율",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "시스템메모리사용율(DB01)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "시스템메모리사용율",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"total\") AS \"total\" FROM \"mem\" WHERE (\"host\" = 'MyLinuxDB01') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "DB Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 1, "w": 17, "x": 0, "y": 18 }, "content": "# title" },
  {
   "title": "DB BASIC INFO",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "altibase_basic_info",
     "select": [
      [
       { "params": [ "DB_NAME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DB_NAME" ], "type": "alias" }
      ],
      [
       { "params": [ "PRODUCT_VERSION" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DB_VERSION" ], "type": "alias" }
      ],
      [
       { "params": [ "DB_UP_TIME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DB_UP_TIME" ], "type": "alias" }
      ],
      [
       { "params": [ "LOG_MODE" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LOG_MODE" ], "type": "alias" }
      ],
      [
       { "params": [ "NLS_CHARACTERSET" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CHARACTERSET" ], "type": "alias" }
      ],
      [
       { "params": [ "STARTUP_PHASE" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "STARTUP_PHASE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "MyLinuxDB01" }
     ]
    }
   ]
  }
 ]
}